services:
  cogitoweb.command.shard_list:
    class: Cogitoweb\ShardManagerBundle\Command\ShardsListCommand
    arguments:
      - '@cogitoweb.repository.company'
    tags:
      - {name: console.command}